services:
  db:
    image: mariadb:lts-ubi10
    container_name: globalapi_db
    restart: always
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  globalapi:
    build: .
    container_name: globalapi
    restart: always
    ports:
      - "3000:3000"
    environment:
      - HOST=db
      - PORT=3306
      - PASSWORD=examplepassword
    depends_on:
      db:
        condition: service_healthy
volumes:
  db_data:  
